In [ ]:
#11주차 원세희 2024141422

In [2]:
import numpy as np

In [13]:
a = np.arange(6)

In [14]:
type(a)

numpy.ndarray

In [15]:
a

array([0, 1, 2, 3, 4, 5])

In [56]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [60]:
a

array([1, 2, 3, 4, 5, 6])

In [61]:
a = np.array([1, 2, 3, 4, 5, 6])

In [62]:
a

array([1, 2, 3, 4, 5, 6])

In [63]:
a[0]

np.int64(1)

In [64]:
a[0]=10

In [65]:
a

array([10,  2,  3,  4,  5,  6])

In [58]:
a.shape

(2, 3)

In [16]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [17]:
a2 = a[np.newaxis, :]

In [18]:
a2.shape

(1, 6)

In [ ]:
#Array fundamentals

In [19]:
a[0] = 10

In [20]:
a

array([10,  1,  2,  3,  4,  5])

In [21]:
a[:3]

array([10,  1,  2])

In [22]:
b = a[3:]

In [23]:
b

array([3, 4, 5])

In [24]:
b[0] = 40

In [25]:
a

array([10,  1,  2, 40,  4,  5])

In [26]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [27]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
print(a[1, 3])

8


In [30]:
a[0]

array([1, 2, 3, 4])

In [ ]:
#Array attributes

In [31]:
a.ndim

2

In [32]:
a.shape

(3, 4)

In [33]:
len(a.shape) == a.ndim

True

In [34]:
a.size

12

In [35]:
import math

In [36]:
a.size == math.prod(a.shape)

True

In [37]:
a.dtype

dtype('int64')

In [ ]:
#How to create a basic array

In [38]:
np.zeros(2)

array([0., 0.])

In [39]:
np.ones(2)

array([1., 1.])

In [40]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

In [41]:
np.arange(4)

array([0, 1, 2, 3])

In [42]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [43]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
x = np.ones(2, dtype=np.int64)

In [45]:
x

array([1, 1])

In [ ]:
#Adding, removing, and sorting elements

In [46]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [47]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
np.argsort(arr)

array([1, 0, 3, 5, 2, 6, 4, 7])

In [49]:
np.lexsort(arr)

np.int64(0)

In [50]:
np.searchsorted(arr)

TypeError: searchsorted() missing 1 required positional argument: 'v'

In [51]:
np.partition(arr)

TypeError: partition() missing 1 required positional argument: 'kth'

In [52]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [53]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [55]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#How do you know the shape and size of an array?

In [3]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [4]:
array_example.ndim

3

In [5]:
array_example.size

24

In [6]:
array_example.shape

(3, 2, 4)

In [ ]:
#Can you reshape an array?

In [7]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [8]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [9]:
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
#How to convert a 1D array into a 2D array

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [11]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [12]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [13]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [14]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
#Indexing and slicing

In [15]:
data = np.array([1, 2, 3])

In [16]:
data[1]

np.int64(2)

In [17]:
data[0:2]

array([1, 2])

In [18]:
data[1:]

array([2, 3])

In [19]:
data[-2:]

array([2, 3])

In [20]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [21]:
print(a[a < 5])

[1 2 3 4]


In [22]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [23]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [24]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [25]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [26]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [27]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [28]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [29]:
print(a[b])

[1 2 3 4]


In [30]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [ ]:
#How to create an array from existing data

In [31]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [33]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [34]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [35]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [36]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [38]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [39]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [40]:
b1 = a[0, :]
b1
b1[0] = 99
b1
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
b2 = a.copy()

In [ ]:
#Basic array operations

In [42]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [43]:
data - ones

array([0, 1])

In [45]:
data * data

array([1, 4])

In [46]:
data / data

array([1., 1.])

In [47]:
a = np.array([1, 2, 3, 4])

In [48]:
a.sum()

np.int64(10)

In [49]:
b = np.array([[1, 1], [2, 2]])

In [50]:
b.sum(axis=0)

array([3, 3])

In [51]:
b.sum(axis=1)

array([2, 4])

In [ ]:
#Broadcasting

In [52]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [ ]:
#More useful array operations

In [53]:
data.max()

np.float64(2.0)

In [54]:
data.min()

np.float64(1.0)

In [55]:
data.sum()

np.float64(3.0)

In [56]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [57]:
a.sum()

np.float64(4.8595784)

In [58]:
a.min()

np.float64(0.05093587)

In [59]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [ ]:
#Creating matrices

In [60]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
data[0, 1]

np.int64(2)

In [62]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [63]:
data[0:2, 0]

array([1, 3])

In [64]:
data.max()

np.int64(6)

In [65]:
data.min()

np.int64(1)

In [66]:
data.sum()

np.int64(21)

In [67]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [68]:
data.max(axis=0)

array([5, 6])

In [69]:
data.max(axis=1)

array([2, 5, 6])

In [71]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [72]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [73]:
np.ones((4, 3, 2))




array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [74]:
np.ones(3)

array([1., 1., 1.])

In [75]:
np.zeros(3)

array([0., 0., 0.])

In [77]:
rng = np.random.default_rng()  # the simplest way to generate random numbers\

In [78]:
rng.random(3) 

array([0.88895763, 0.24530528, 0.3688254 ])

In [79]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [80]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [81]:
rng.random((3, 2)) 

array([[0.63118032, 0.49489724],
       [0.90525225, 0.24751097],
       [0.28958682, 0.67825077]])

In [ ]:
#Generating random numbers

In [82]:
rng.integers(5, size=(2, 4)) 

array([[1, 1, 0, 0],
       [1, 0, 2, 2]])

In [ ]:
#How to get unique items and counts

In [83]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [84]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [85]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [86]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [87]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [88]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [89]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [90]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [91]:
print(indices)

[0 1 2]


In [92]:
print(occurrence_count)

[2 1 1]


In [ ]:
#Transposing and reshaping a matrix

In [93]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [96]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [97]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
#How to reverse an array

In [98]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [99]:
reversed_arr = np.flip(arr)

In [100]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [101]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [102]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [103]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [104]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [105]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [106]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [ ]:
#Reshaping and flattening multidimensional arrays

In [107]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [108]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [109]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [110]:
print(a1)  # New array

[99  2  3  4  5  6  7  8  9 10 11 12]


In [111]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [112]:
print(a2)  # New array

[98  2  3  4  5  6  7  8  9 10 11 12]
